#spring.datasource.url=${DATABASE_URL}
#spring.data.redis.url=${REDIS_URL}

spring.datasource.url=jdbc:postgresql://localhost:5432/bada_bazaar?user=postgres&password=postgres
spring.data.redis.url=redis://localhost:6379