server.port=8080

#===================MongoDB====================#
spring.data.mongodb.uri=mongodb://localhost:27017/bazarDB
#spring.data.mongodb.uri=mongodb+srv://amoln:amol123@cluster0.yr4i7p8.mongodb.net/bazarDB?retryWrites=true&w=majority


#===================Actuator====================#
management.endpoints.web.exposure.include=*


#===================Redis====================#
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=

#===================Swagger====================#

#===================Placeholders====================#

#===================Elastic====================#


#===================Kafka====================#
