
#### MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/bazarDB
#spring.data.mongodb.uri=mongodb+srv://amoln:amol123@cluster0.yr4i7p8.mongodb.net/bazarDB?retryWrites=true&w=majority

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

### Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amolnakhate240@gmail.com
spring.mail.password=egmxynhdkgcohfna
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


### Consul Config
spring.applicaton.name=BadaBazaar
spring.config.import=optional:consul:
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.name=BadaBazaar
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500